name: "Run Unit Tests"

on:  
  push:
    branches: 
      - main
      - development
      - feature/**
      
jobs:
  build:      
    runs-on: ubuntu-latest
    timeout-minutes: 5    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
    - name: Build
      run: dotnet build ./Water\ Drink\ Water/Water\ Drink\ Water.sln -c Release
    - name: Test
      run: dotnet test ./Water\ Drink\ Water/Water\ Drink\ Water.sln -c Release --no-build     